# Kustomize v2.1からはbasesはresourcesに統合(deprecatedになった)
bases:
- ../../base
# 適用するリソース
resources:
- ingress/ingress.yaml
# baseリソースに対して適用するPatchファイル群
patchesStrategicMerge:
- api-gateway/replicas_patch.yaml
- api-gateway/resources_patch.yaml
- api-gateway/appinsights-key_patch.yaml
- github-service/replicas_patch.yaml
- github-service/resources_patch.yaml
- github-service/appinsights-key_patch.yaml
- github-service/logback_patch.yaml
- repo-search-ui/replicas_patch.yaml
- repo-search-ui/resources_patch.yaml
# Secretリソース
secretGenerator:
- name: github-secret
  files:
  - user=.env/github-user
  - password=.env/github-pass
- name: redis-secret
  files:
  - password=.env/redis-pass
# ConfigMapリソース
configMapGenerator:
- name: api-gateway-config
  literals:
  - serviceURL=http://github-service/github
  # Azure Redis for Cache
  - redisHost=friezaRedis.redis.cache.windows.net
  - redisPort=6379
- name: github-logback
  files:
    - github-service/logback.xml
# コンテナイメージ
images:
- name: api-gateway
  newName: friezaregistry.azurecr.io/api-gateway
  newTag: v1
- name: github-service
  newName: friezaregistry.azurecr.io/github-service
  newTag: v1
- name: repo-search-ui
  newName: friezaregistry.azurecr.io/repo-search-ui
  newTag: v1