apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-service
spec:
  template:
    spec:
      containers:
      - name: github-service
        env:
        - name: AZURE_APPLICATIONINSIGHTS_ENABLED
          value: "true"
        - name: AZURE_APPLICATIONINSIGHTS_WEB_ENABLED
          value: "true"
        - name: MANAGEMENT_METRICS_EXPORT_AZUREMONITOR_ENABLED
          value: "true"
        - name: APP_INSIGHTS_KEY
          value: 3701c519-c49d-4d06-824b-06e85a9025c5
